[build]
  command = "npm run build:netlify"
  publish = "dist/client"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

  # Specify external Node modules that should not be bundled
  external_node_modules = ["dotenv", "firebase", "node-fetch"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200