[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  # Environment variables for build process
  NEXT_TELEMETRY_DISABLED = "1"

# Enable the Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for API routes and SPA behavior
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Catch-all redirect for client-side routing (Next.js SPA fallback)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"