[build]
  command = "npm run build:netlify"
  publish = "dist/client"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["dotenv", "firebase"]

[[plugins]]
  package = "./netlify/plugins/install-function-dependencies"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200